name: beans
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  gradient_app_bar: ^0.1.3
  gradient_widgets: ^0.5.1
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ic_time.svg
    - assets/ic_home.svg
    - assets/ic_god.png
    - assets/ic_money.svg
    - assets/ic_human_rights.svg
    - assets/ic_myself.png
    - assets/ic_arrow_next.svg
    - assets/ic_add.svg
    - assets/ic_calendar.svg
    - assets/ic_confession.svg
    - assets/ic_bean.svg
    - assets/ic_black_bean.svg
    - assets/ic_other_guys.png
    - assets/ic_health.svg
    - assets/tooltip.png
    - assets/ic_white_bean.svg
    - assets/ic_more.svg
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
