name: beans
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  gen_lang: ^0.1.3
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/ic_home.svg
    - assets/ic_calendar.svg
    - assets/ic_confession.svg
    - assets/ic_bean.svg
    - assets/ic_god.svg
    - assets/ic_my_self.svg
    - assets/ic_other_guys.svg
    - assets/tooltip.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
